### PR TITLE
Hafidh oddle qa challenge

### PR DESCRIPTION
**Pull request by Hafidh1989**

### CODE REVIEW

**Comment by oddle-developer** [comment]
@Hafidh1989 I left some comments in the PR. 

Additionally I have these questions as well:
1. Why did you choose Cucumber? What are the advantages/disadvantages of Cucumber compared to other tools?
2. How would you integrate this test in a CI/CD pipeline?

**Comment by Hafidh1989** [comment]
> @Hafidh1989 I left some comments in the PR.
> 
> Additionally I have these questions as well:
> 
> 1. Why did you choose Cucumber? What are the advantages/disadvantages of Cucumber compared to other tools?
> 2. How would you integrate this test in a CI/CD pipeline?

1. Why I choose cucumber?because I think it's readable for everyone. all people can just read the feature file and they know what is being tested, and also it's gherkin style
2. actually I never put my hand directly to put automation test on the repo. but back then when I asked my devops to integrate it on CI/CD which they use portainer, he just asked me to make sure the test can be run through cmd. just type mvn test and it will execute the test. hope it answered your question

image
image

**Comment by Hafidh1989** [comment]
Hi Andi

I just answered your question on the PR.
Thank you

**Comment by oddle-developer** [comment]
@Hafidh1989 apart from these two questions above, I added some comments/review questions on the PR itself. Please check them.

**Comment by Hafidh1989** [comment]
> @Hafidh1989 apart from these two questions above, I added some comments/review questions on the PR itself. Please check them.

@oddle-developer hi, I cant find your comment 
https://drive.google.com/file/d/1yLJvWWWAm-y9ueTIyBGcYbMU_E40IkK2/view?usp=sharing

**Comment by oddle-developer** [comment]
@Hafidh1989 Not sure why they did not appear for you. In any case, I listed them below:
1. In `src/test/java/Helpers/Pages.java`, could you please explain why you chose to use By,xpath when there is id available?
2. In `OneTimeDonationSteps.java`, how would you parameterize the step?
3. What would be a good reporting option apart from the one used in this PR, and how would you integrate it?

**Comment by Hafidh1989** [comment]
> @Hafidh1989 Not sure why they did not appear for you. In any case, I listed them below:
> 
> 1. In `src/test/java/Helpers/Pages.java`, could you please explain why you chose to use By,xpath when there is id available?
> 2. In `OneTimeDonationSteps.java`, how would you parameterize the step?
> 3. What would be a good reporting option apart from the one used in this PR, and how would you integrate it?

hi @oddle-developer 
1. I think its only my prefrence, because I get used to use xpath to find an element
2. I would say like this if I want to parameterize the steps.
on feature file
Given I want to go to 'www.google.com'
then on the steps.java file
`
@Given(I want to go to {string}")
public void i_have_red_balls(String url) {
driver.get(url);
}
3. I think the other approach for reporting is try to generate testng.xml
`

**Pull request merged**
